#docker
version: "3.9"
services:
    jax_service:
        image: jax_service
        build: .
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 2
                          capabilities: [gpu]